baseURL = 'https://gohugo.io/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "LoquendoAlert"
hostname = "Devs"
  [params.author]
    name = "Loquendo Alert Devs"  # Website and RSS feed author
    email = "#"  # RSS feed email address


readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/LoquendoAlertCreators"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/@alertlel"
aria = "Twitter Profile"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.example.com"
aria = "LinkedIn Profile"

[[params.social]]
key = 3
name = "email"
url = "#"
aria = "My e-Mail Address"
